aliases:
  - &restore-npm-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-dependencies-{{ .Branch }}-          # fallback to using the latest cache if no exact match is found

  - &save-npm-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

  - &update-npm
      |
      sudo npm install -g npm@6.1.0

  - &install-dependencies
    |
      npm install

  - &attach-workspace
    at: ~/fomes-admin-frontend

  - &delivery-dist
    root: .
    paths: dist

  - &setup-heroku
    name: Setup Heroku
    command: bash .circleci/setup-heroku.sh $HEROKU_APP

  - &setup-branch-and-commit
    name: Setup Branch and Commit
    command: |
      bash .circleci/setup-branch-and-commit.sh heroku-$HEROKU_APP

  - &deploy-to-heroku
    name: Deploy to Heroku
    command: |
      ls; ls dist
      git push -v heroku `git subtree split --prefix=dist -b heroku-$HEROKU_APP-deploy`:master --force
      sleep 5
      heroku restart

  - &filter-master-branch
    branches:
      only:
        - master
  - &filter-release-branch
    branches:
      only:
        - release

defaults: &defaults
    working_directory: ~/fomes-admin-frontend # directory where steps will run
    docker:
      - image: circleci/node:8.11

version: 2
jobs:
####### TODO : move to a shell script for build
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: *attach-workspace
      - run: *update-npm
      - restore_cache: *restore-npm-cache
      - run: *install-dependencies
      - save_cache: *save-npm-cache
      # Test
      - run:
          name: test
          command: npm test

  dev-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: *attach-workspace
      - run: *update-npm
      - restore_cache: *restore-npm-cache
      - run: *install-dependencies
      - save_cache: *save-npm-cache
      - run:
          name: set environment variables at Runtime
          command: |
            echo 'export BASE_URL=$DEV_BASE_URL' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build in Development Mode
          command: npm run build-dev
      - persist_to_workspace: *delivery-dist
      - run:
          name: check dist directory
          command: pwd; ls; ls dist

  stg-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: *attach-workspace
      - run: *update-npm
      - restore_cache: *restore-npm-cache
      - run: *install-dependencies
      - save_cache: *save-npm-cache
      - run:
          name: set environment variables at Runtime
          command: |
            echo 'export BASE_URL=$DEV_BASE_URL' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build in Production Mode
          command: npm run build
      - persist_to_workspace: *delivery-dist
      - run:
          name: check dist directory
          command: pwd; ls; ls dist

  prd-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: *attach-workspace
      - run: *update-npm
      - restore_cache: *restore-npm-cache
      - run: *install-dependencies
      - save_cache: *save-npm-cache
      - run:
          name: set environment variables at Runtime
          command: |
            echo 'export BASE_URL=$DEV_BASE_URL' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build in Production Mode
          command: npm run build
      - persist_to_workspace: *delivery-dist
      - run:
          name: check dist directory
          command: pwd; ls; ls dist

  # Deploy
  dev-deploy:
    <<: *defaults
    environment:
    - HEROKU_APP: fomes-admin-frontend-dev
    steps:
    - checkout
    - attach_workspace: *attach-workspace
    - run: *setup-heroku
    - run: *setup-branch-and-commit
    - run: *deploy-to-heroku
    - persist_to_workspace: *delivery-dist

  stg-deploy:
    <<: *defaults
    environment:
      - HEROKU_APP: fomes-admin-frontend-stg
    steps:
      - checkout
      - attach_workspace: *attach-workspace
      - run: *setup-heroku
      - run: *setup-branch-and-commit
      - run: *deploy-to-heroku

  prd-deploy:
    <<: *defaults
    environment:
    - HEROKU_APP: fomes-admin-frontend
    steps:
    - checkout
    - attach_workspace: *attach-workspace
    - run: *setup-heroku
    - run: *setup-branch-and-commit
    - run: *deploy-to-heroku

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - dev-build:
          requires:
            - test
          filters: *filter-master-branch
      - dev-deploy:
          requires:
            - test
            - dev-build
          filters: *filter-master-branch
      - stg-build:
          requires:
            - test
          filters: *filter-master-branch
      - stg-deploy:
          requires:
            - test
            - stg-build
          filters: *filter-master-branch
      - prd-build:
          requires:
            - test
          filters: *filter-release-branch
      - prd-deploy:
          requires:
            - test
            - prd-build
          filters: *filter-release-branch
